name: ClearChat
main: ClearChat\ClearChat\Main
version: 1.1
api: [3.0.0-ALPHA11, 3.0.0-ALPHA12]
description: Clear chat, based of VMPE.
commands:
    cc:
        description: Clears chat publicly
        permission: chatclear.clear
permissions:
  clearchat.clear:
    default: false
