name: ClearChat
main: ClearChat\ClearChat\Main
version: 1.1
api: [3.0.0-ALPHA11]
commands:
    cc:
     description: Clear Chat
     permission: clearchat.clear
 permissions:
  clearchat.clear:
    default: op
